### ISSUE TITLE
DB review

### ISSUE THREAD

**Issue by gootieno** [natoh19/SoundOm#1]
Hi! I was looking to review your schema but I don't believe it was loaded into the wiki schema section. If you get a chance in the morning go ahead and provide the correct link and we will get it reviewed asap! Thank you! Let us know if there are any issues.

**Comment by natoh19** [comment]
Hi Gregory. Do you mean this? I published this on Saturday. Is it not in the right place? https://github.com/natoh19/SoundOm/wiki/Database-Schema

**Comment by natoh19** [comment]
Maybe you mean the chart ? [Link to DB Schema](https://dbdiagram.io/d/6066520fecb54e10c33e5fb0)

**Comment by natoh19** [comment]
Everything is resolved now I think.
